os: linux
services:
   - docker
sudo: required
language: python
env:
  global:
    - CONAN_UPLOAD=1
    - CONAN_REFERENCE="lksctp-tools/1.0.17"
    - CONAN_USERNAME="uilianries"
    - CONAN_CHANNEL="ci"
    - CONAN_TOTAL_PAGES=1
    - CONAN_CURRENT_PAGE=1
    - CONAN_STABLE_BRANCH_PATTERN="release/*"

matrix:
   include:
       - os: osx
         osx_image: xcode8.2 # apple-clang 8.2
         language: generic
         env:
       - os: osx
         osx_image: xcode8.1 # apple-clang 8.1
         language: generic
         env:
       - os: osx
         osx_image: xcode8 # apple-clang 8.0
         language: generic
         env:
       - os: osx
         osx_image: xcode7.3 # apple-clang 7.3
         language: generic
         env:
       - os: osx
         osx_image: xcode7.1 # apple-clang 7.0
         language: generic
         env:
       - os: osx
         osx_image: xcode6.4 # apple-clang 6.1
         language: generic
         env:
       - os: osx
         osx_image: xcode6.2 # apple-clang 6.0
         language: generic
         env:

install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh
  
